DROP TABLE IF EXISTS example.PET_TAG_ASS;
DROP TABLE IF EXISTS example.TAG;
DROP TABLE IF EXISTS example.PET_PHOTO_ASS;
DROP TABLE IF EXISTS example.PHOTO;
DROP TABLE IF EXISTS example.PET;
DROP TABLE IF EXISTS example.CATEGORY;

CREATE TABLE example.CATEGORY(
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  CATEGORY_NAME VARCHAR(255) UNIQUE
);

CREATE TABLE example.PET(
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  CATEGORY_ID BIGINT REFERENCES CATEGORY(ID),
  PET_NAME VARCHAR(255) NOT NULL,
  STATUS VARCHAR(255) NOT NULL
);

CREATE TABLE example.PHOTO(
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  PHOTO_URL VARCHAR(255) NOT NULL
);

CREATE TABLE example.PET_PHOTO_ASS(
  PET_ID BIGINT REFERENCES PET(ID),
  PHOTO_ID BIGINT REFERENCES PHOTO(ID)
);

CREATE TABLE example.TAG(
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  TAG_NAME VARCHAR(255) NOT NULL,
  LTAG_NAME VARCHAR(255) UNIQUE
);

CREATE TABLE example.PET_TAG_ASS(
  PET_ID BIGINT REFERENCES PET(ID),
  TAG_ID BIGINT REFERENCES TAG(ID)
);
